nodeLinker: node-modules

npmScopes:
  robustive:
    npmAlwaysAuth: true
    npmAuthToken: "${GITHUB_TOKEN}"
    npmPublishRegistry: "https://npm.pkg.github.com"
    npmRegistryServer: "https://npm.pkg.github.com"
